name: "Publish to AWS CodeArtifact"
description: "Publish built wheels and sdist to AWS CodeArtifact"
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: dist
    - name: Get AWS token
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: eu-west-2
        role-to-assume: "arn:aws:iam::939792010034:role/registry_deploy"
    - name: List dist folder contents
      shell: bash
      run: ls -la dist
    - name: Publish to CodeArtifact
      shell: bash
      run: |
        aws codeartifact login \
          --tool twine \
          --repository hace-pypi-registry \
          --domain hace-package-registry \
          --domain-owner 939792010034 && \
        python3 -m pip install --upgrade pip twine && \
        python3 -m twine upload dist/*
