[package]
name = "processor_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
lazy_static = "1.5.0"
porter-stemmer = "0.1.2"
rayon = "1.10.0"
regex = "1.11.1"
thiserror = "2.0.3"
