name: Publish
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
permissions:
  id-token: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/codeartifact_publish
