name: Publish
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/codeartifact_publish
