name: Publish
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  linux:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_wheels
        with:
          os: linux
          target: ${{ matrix.platform.target }}
  macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-14
            target: x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_wheels
        with:
          os: macos
          target: ${{ matrix.platform.target }}
  sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_sdist
  publish:
    runs-on: ubuntu-latest
    needs: [linux, macos, sdist]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/codeartifact_publish
