name: Test and Build
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/unit_test
  linux:
    runs-on: ${{ matrix.platform.runner }}
    needs: test
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64
          - runner: ubuntu-latest
            target: x86
          - runner: ubuntu-latest
            target: aarch64
          - runner: ubuntu-latest
            target: armv7
          - runner: ubuntu-latest
            target: s390x
          - runner: ubuntu-latest
            target: ppc64le
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_wheels
        with:
          os: linux
          target: ${{ matrix.platform.target }}
  macos:
    runs-on: ${{ matrix.platform.runner }}
    needs: test
    strategy:
      matrix:
        platform:
          - runner: macos-12
            target: x86_64
          - runner: macos-14
            target: aarch64
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_wheels
        with:
          os: macos
          target: ${{ matrix.platform.target }}
  sdist:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/build_sdist
